library/book/urls.py
"""
URLs mapping for book app
"""

from django.urls import path
from . import views


app_name = 'book'


urlpatterns = [
    path('', views.view_set, name='all'),
    path('<int:book_id>/', views.detail_view, name='detail'),
    path('search/', views.view_books_by_user, name='search'),
]

library/library/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView


urlpatterns = [
    path('', include('core.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('books/', include('book.urls')),
    path('authors/', include('author.urls')),
    path('orders/', include('order.urls')),
    path('users/', include('users.urls')),
    path('api/v1/', include('api_v1.urls')),
]

library/book/models.py
from django.db import models


class Book(models.Model):
    """
        This class represents an Author. \n
        Attributes:
        -----------
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
    """
    name = models.CharField(blank=True, max_length=128)
    description = models.CharField(blank=True, max_length=256)
    count = models.IntegerField(default=10)
    id = models.AutoField(primary_key=True)
    date_of_issue = models.DateField(blank=True, null=True, default=None)

    def __str__(self):
        """
        Magic method is redefined to show all information about Book.
        :return: book id, book name, book description, book count, book authors
        """
        return f"{self.name}"

    def __repr__(self):
        """
        This magic method is redefined to show class and id of Book object.
        :return: class, id
        """
        return f"Book(id={self.id})"

    @staticmethod
    def get_by_id(book_id):
        """
        :param book_id: SERIAL: the id of a Book to be found in the DB
        :return: book object or None if a book with such ID does not exist
        """
        return Book.objects.get(id=book_id) if Book.objects.filter(id=book_id) else None

    @staticmethod
    def delete_by_id(book_id):
        """
        :param book_id: an id of a book to be deleted
        :type book_id: int
        :return: True if object existed in the db and was removed or False if it didn't exist
        """
        if Book.get_by_id(book_id) is None:
            return False
        Book.objects.get(id=book_id).delete()
        return True

    @staticmethod
    def create(name, description, count=10, authors=None):
        """
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        param authors: list of Authors
        type authors: list->Author
        :return: a new book object which is also written into the DB
        """
        if len(name) > 128:
            return None

        book = Book()
        book.name = name
        book.description = description
        book.count = count
        if (authors is not None):
            for elem in authors:
                book.authors.add(elem)
        book.save()
        return book

    def to_dict(self):
        """
        :return: book id, book name, book description, book count, book authors
        :Example:
        | {
        |   'id': 8,
        |   'name': 'django book',
        |   'description': 'bla bla bla',
        |   'count': 10',
        |   'authors': []
        | }
        """

    def update(self, name=None, description=None, count=None):
        """
        Updates book in the database with the specified parameters.\n
        param name: Describes name of the book
        type name: str max_length=128
        param description: Describes description of the book
        type description: str
        param count: Describes count of the book
        type count: int default=10
        :return: None
        """
        if name is not None:
            self.name = name

        if description is not None:
            self.description = description

        if count is not None:
            self.count = count

        self.save()

    def add_authors(self, authors):
        """
        Add  authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        if (authors is not None):
            for elem in authors:
                self.authors.add(elem)
                self.save()

    def remove_authors(self, authors):
        """
        Remove authors to  book in the database with the specified parameters.\n
        param authors: list authors
        :return: None
        """
        for elem in self.authors.values():
            self.authors.remove(elem['id'])

    @staticmethod
    def get_all():
        """
        returns data for json request with QuerySet of all books
        """
        return list(Book.objects.all())

library/book/views.py
"""
Views for book
"""
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from .models import Book
from author.models import Author
from order.models import Order
from django.http import HttpResponseForbidden
from authentication.models import CustomUser
from authentication.forms import SearchUserById


@login_required()
def view_set(request):
    """All books view"""
    filter_data = dict()
    books = Book.objects.all()

    if request.GET.get('author'):
        try:
            filter_data['author'] = int(request.GET.get('author'))
        except ValueError as e:
            print(e)
        else:
            books = books.filter(authors__in=[filter_data['author']])
    if request.GET.get('book'):
        try:
            filter_data['book'] = int(request.GET.get('book'))
        except ValueError as e:
            print(e)
        else:
            books = books.filter(pk=filter_data['book'])

    authors = Author.objects.filter(books__in=books).distinct()

    return render(request, 'book/all.html', {'books': books,
                                             'authors': authors,
                                             'filter_data': filter_data})


@login_required()
def detail_view(request, book_id):
    """Detail book view"""
    book = get_object_or_404(Book, pk=book_id)
    return render(request, 'book/detail.html', {'book': book})


@login_required()
def view_books_by_user(request):
    """All books by user view - only for librarian"""
    if request.user.role != 1:
        return HttpResponseForbidden()

    if request.method == 'GET':
        form = SearchUserById()
        return render(request, 'book/book_by_user.html', {'search_form': form})

    if request.method == 'POST':
        form = SearchUserById(request.POST)
        res = ''
        search_query = ''
        if form.is_valid():
            search_query = form.cleaned_data['user_id']
            res = Order.objects.filter(user__pk=search_query)\
                .select_related('book').order_by('-end_at')

        return render(request, 'book/book_by_user.html',
                      {'search_query': search_query,
                       'orders': res,
                       'search_form': form})

library/templates/book/all.html
{% extends 'base/base.html' %}
{% block meta_title %}Books{% endblock %}
{% block title %}Books{% endblock %}
{% block content %}
    <div>
        <form action="" method="GET" class="row">
            <div class="col-xl-4 col-lg-6 col-12">
                <select class="form-select "
                        id="filterAuthor" name="author" onchange="this.form.submit()">
                    <option selected>All authors</option>
                    {% for author in authors %}
                        <option value="{{ author.id }}"
                                {% if author.id == filter_data.author %}selected{% endif %}>{{ author.name|title }}</option>
                    {% endfor %}
                </select>
            </div>
            <div class="col-xl-4 col-lg-6 col-12">
                <select class="form-select "
                        id="filterTitle" name="book" onchange="this.form.submit()">
                    <option selected>All books</option>
                    {% for book in books %}
                        <option value="{{ book.id }}"
                                {% if book.id == filter_data.book %}selected{% endif %}>{{ book.name|title }}</option>
                    {% endfor %}
                </select>
            </div>
        </form>
    </div>
    <div class="row">
        {% for book in books %}
            <div class=" p-4 col-xl-4 col-lg-6 col-12">
             <div class="border">
                 <div>
                     <img src="https://cdn.shopify.com/s/files/1/0024/6874/1219/products/WitcherAndrzejSapkowski8Books-Banded-B2D2634-front3-jpg_compressed_ba150cfc-6299-43a5-8a4a-d323feabd5d3_700x700.jpg?v=1658580009" class="mw-100">
                 </div>
                 <div class="p-2 border-bottom">
                     <h4 class="m-0">{{ book.name }}</h4>
                 </div>
                 <div class="p-2 text-secondary">
                     <small>{{ book.description }}</small>
                 </div>
                 <div class="p-2 text-end" >
                     <a href="{% url 'book:detail' book.id %}" class="inline link-primary">Detail</a>
                 </div>

             </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

library/templates/book/book_by_user.html
{% extends 'base/base.html' %}
{% block meta_title %}Books by user{% endblock %}
{% block title %}Books by user{% endblock %}
{% block content %}
    <div>
        <form action="" method="POST">
            <div class="input-group mb-3">
                {% csrf_token %}
                {% for field in search_form %}
                    {{ field }}
                {% endfor %}
                <div class="input-group-append">
                    <button class="btn btn-outline-secondary" type="submit">Button</button>
                </div>
            </div>
        </form>
    </div>
    {% if search_form.errors %}
        {% for field_name, errors in search_form.errors.items %}
            {% for error in errors %}
                <div class=" text-center"><small class="text-danger">{{ error }}</small></div>
            {% endfor %}

        {% endfor %}
    {% endif %}

    {% if search_query and not query_error %}<h4 class="text-center">Search results for user with id: {{ search_query }}</h4>{% endif %}
    <div class="row">
        {% for order in orders %}
            <div class=" p-4 col-xl-4 col-lg-6 col-12">
             <div class="border {% if order.end_at is None %}border-warning{% endif %}">
                 <div>
                     <img src="https://cdn.shopify.com/s/files/1/0024/6874/1219/products/WitcherAndrzejSapkowski8Books-Banded-B2D2634-front3-jpg_compressed_ba150cfc-6299-43a5-8a4a-d323feabd5d3_700x700.jpg?v=1658580009" class="mw-100">
                 </div>
                 <div class="p-2 border-bottom">
                     <h4 class="m-0">{{ order.book.name }}</h4>
                 </div>
                 <div class="p-2 text-secondary">
                     <small><b>Book id: </b>{{ order.book.id }}</small>
                 </div>
                 <div class="p-2 text-secondary">
                     <small><b>Created at: </b>{{ order.created_at }}</small>
                 </div>
                 <div class="p-2 text-secondary">
                     <small><b>End at: </b>{{ order.end_at }}</small>
                 </div>
                 <div class="p-2 text-secondary">
                     <small><b>Plated end at: </b>{{ order.plated_end_at }}</small>
                 </div>


             </div>

            </div>
        {% endfor %}
    </div>
{% endblock %}

library/templates/book/detail.html
{% extends 'base/base.html' %}
{% block meta_title %}{{ book.name }}{% endblock %}
{% block title %}{{ book.name }}{% endblock %}
{% block content %}
    <div class="row">
        <div class="col-xl-6 p-2">
            <img src="https://cdn.shopify.com/s/files/1/0024/6874/1219/products/WitcherAndrzejSapkowski8Books-Banded-B2D2634-front3-jpg_compressed_ba150cfc-6299-43a5-8a4a-d323feabd5d3_700x700.jpg?v=1658580009" class="mw-100">
        </div>
        <div class="col-xl-6 p-2">
            <p><b>Author:</b> {% for author in book.authors.all %}{{ author.name }}{% endfor %}</p>
            <p><b>Description</b> {{ book.description }}</p>
        </div>
    </div>

{% endblock %}